libs-y += uacpi

uacpi-y += libs/uACPI/source/tables.c
uacpi-y += libs/uACPI/source/types.c
uacpi-y += libs/uACPI/source/uacpi.c
uacpi-y += libs/uACPI/source/utilities.c
uacpi-y += libs/uACPI/source/interpreter.c
uacpi-y += libs/uACPI/source/opcodes.c
uacpi-y += libs/uACPI/source/namespace.c
uacpi-y += libs/uACPI/source/stdlib.c
uacpi-y += libs/uACPI/source/shareable.c
uacpi-y += libs/uACPI/source/opregion.c
uacpi-y += libs/uACPI/source/default_handlers.c
uacpi-y += libs/uACPI/source/io.c
uacpi-y += libs/uACPI/source/notify.c
uacpi-y += libs/uACPI/source/sleep.c
uacpi-y += libs/uACPI/source/registers.c
uacpi-y += libs/uACPI/source/resources.c
uacpi-y += libs/uACPI/source/event.c
uacpi-y += libs/uACPI/source/mutex.c
uacpi-y += libs/uACPI/source/osi.c

cflags-uacpi-y += -Ilibs/uACPI/include
