#include "except.h"

const char* get_error_name(err_t err) {
    switch (err) {
        case WASI_ERRNO_SUCCESS: return "No error occurred. System call completed successfully.";
        case WASI_ERRNO_2BIG: return "Argument list too long.";
        case WASI_ERRNO_ACCES: return "Permission denied.";
        case WASI_ERRNO_ADDRINUSE: return "Address in use.";
        case WASI_ERRNO_ADDRNOTAVAIL: return "Address not available.";
        case WASI_ERRNO_AFNOSUPPORT: return "Address family not supported.";
        case WASI_ERRNO_AGAIN: return "Resource unavailable, or operation would block.";
        case WASI_ERRNO_ALREADY: return "Connection already in progress.";
        case WASI_ERRNO_BADF: return "Bad file descriptor.";
        case WASI_ERRNO_BADMSG: return "Bad message.";
        case WASI_ERRNO_BUSY: return "Device or resource busy.";
        case WASI_ERRNO_CANCELED: return "Operation canceled.";
        case WASI_ERRNO_CHILD: return "No child processes.";
        case WASI_ERRNO_CONNABORTED: return "Connection aborted.";
        case WASI_ERRNO_CONNREFUSED: return "Connection refused.";
        case WASI_ERRNO_CONNRESET: return "Connection reset.";
        case WASI_ERRNO_DEADLK: return "Resource deadlock would occur.";
        case WASI_ERRNO_DESTADDRREQ: return "Destination address required.";
        case WASI_ERRNO_DOM: return "Mathematics argument out of domain of function.";
        case WASI_ERRNO_DQUOT: return "Reserved.";
        case WASI_ERRNO_EXIST: return "File exists.";
        case WASI_ERRNO_FAULT: return "Bad address.";
        case WASI_ERRNO_FBIG: return "File too large.";
        case WASI_ERRNO_HOSTUNREACH: return "Host is unreachable.";
        case WASI_ERRNO_IDRM: return "Identifier removed.";
        case WASI_ERRNO_ILSEQ: return "Illegal byte sequence.";
        case WASI_ERRNO_INPROGRESS: return "Operation in progress.";
        case WASI_ERRNO_INTR: return "Interrupted function.";
        case WASI_ERRNO_INVAL: return "Invalid argument.";
        case WASI_ERRNO_IO: return "I/O error.";
        case WASI_ERRNO_ISCONN: return "Socket is connected.";
        case WASI_ERRNO_ISDIR: return "Is a directory.";
        case WASI_ERRNO_LOOP: return "Too many levels of symbolic links.";
        case WASI_ERRNO_MFILE: return "File descriptor value too large.";
        case WASI_ERRNO_MLINK: return "Too many links.";
        case WASI_ERRNO_MSGSIZE: return "Message too large.";
        case WASI_ERRNO_MULTIHOP: return "Reserved.";
        case WASI_ERRNO_NAMETOOLONG: return "Filename too long.";
        case WASI_ERRNO_NETDOWN: return "Network is down.";
        case WASI_ERRNO_NETRESET: return "Connection aborted by network.";
        case WASI_ERRNO_NETUNREACH: return "Network unreachable.";
        case WASI_ERRNO_NFILE: return "Too many files open in system.";
        case WASI_ERRNO_NOBUFS: return "No buffer space available.";
        case WASI_ERRNO_NODEV: return "No such device.";
        case WASI_ERRNO_NOENT: return "No such file or directory.";
        case WASI_ERRNO_NOEXEC: return "Executable file format error.";
        case WASI_ERRNO_NOLCK: return "No locks available.";
        case WASI_ERRNO_NOLINK: return "Reserved.";
        case WASI_ERRNO_NOMEM: return "Not enough space.";
        case WASI_ERRNO_NOMSG: return "No message of the desired type.";
        case WASI_ERRNO_NOPROTOOPT: return "Protocol not available.";
        case WASI_ERRNO_NOSPC: return "No space left on device.";
        case WASI_ERRNO_NOSYS: return "Function not supported.";
        case WASI_ERRNO_NOTCONN: return "The socket is not connected.";
        case WASI_ERRNO_NOTDIR: return "Not a directory or a symbolic link to a directory.";
        case WASI_ERRNO_NOTEMPTY: return "Directory not empty.";
        case WASI_ERRNO_NOTRECOVERABLE: return "State not recoverable.";
        case WASI_ERRNO_NOTSOCK: return "Not a socket.";
        case WASI_ERRNO_NOTSUP: return "Not supported, or operation not supported on socket.";
        case WASI_ERRNO_NOTTY: return "Inappropriate I/O control operation.";
        case WASI_ERRNO_NXIO: return "No such device or address.";
        case WASI_ERRNO_OVERFLOW: return "Value too large to be stored in data type.";
        case WASI_ERRNO_OWNERDEAD: return "Previous owner died.";
        case WASI_ERRNO_PERM: return "Operation not permitted.";
        case WASI_ERRNO_PIPE: return "Broken pipe.";
        case WASI_ERRNO_PROTO: return "Protocol error.";
        case WASI_ERRNO_PROTONOSUPPORT: return "Protocol not supported.";
        case WASI_ERRNO_PROTOTYPE: return "Protocol wrong type for socket.";
        case WASI_ERRNO_RANGE: return "Result too large.";
        case WASI_ERRNO_ROFS: return "Read-only file system.";
        case WASI_ERRNO_SPIPE: return "Invalid seek.";
        case WASI_ERRNO_SRCH: return "No such process.";
        case WASI_ERRNO_STALE: return "Reserved.";
        case WASI_ERRNO_TIMEDOUT: return "Connection timed out.";
        case WASI_ERRNO_TXTBSY: return "Text file busy.";
        case WASI_ERRNO_XDEV: return "Cross-device link.";
        case WASI_ERRNO_NOTCAPABLE: return "Extension: Capabilities insufficient.";
        default: return "Unknown Error";
    }
}
