#pragma once

#include <stddef.h>
#include <stdint.h>

typedef enum syscall {
	SYSCALL_DEBUG_PRINT,

	SYSCALL_HEAP_ALLOC,
	SYSCALL_HEAP_FREE,

	SYSCALL_JIT_ALLOC,
	SYSCALL_JIT_LOCK_PROTECTION,
	SYSCALL_JIT_FREE,

	SYSCALL_THREAD_CREATE,
	SYSCALL_THREAD_SLEEP,
	SYSCALL_THREAD_EXIT,

	SYSCALL_MEM_RESERVE,
	SYSCALL_MEM_MAP_PHYS,
	SYSCALL_MEM_BUMP,
	SYSCALL_MEM_RELEASE,

	SYSCALL_ATOMIC_WAIT32,
	SYSCALL_ATOMIC_WAIT64,
	SYSCALL_ATOMIC_NOTIFY,

	SYSCALL_EARLY_GET_INITRD_SIZE,
	SYSCALL_EARLY_GET_INITRD,
	SYSCALL_EARLY_DONE,
} syscall_t;
